# Generated by Django 5.2.6 on 2025-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_aisle_number', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=100)),
                ('product_type_hint', models.CharField(blank=True, max_length=200, null=True)),
                ('product_category', models.CharField(max_length=200)),
                ('product_spoof_of', models.CharField(blank=True, max_length=200, null=True)),
                ('game_difficulty', models.CharField(max_length=50)),
                ('additional_notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
